services:
  redis:
    image: redis:alpine
    container_name: redis_rtm
    restart: always
    ports:
      - 6379:6379
  
  postgres:
    image: postgres:alpine
    container_name: postgres_rtm
    shm_size: 1g
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bd_rtm
    volumes:
      - ~/Documentos/Proyectos/RT-dbs/postgres:/var/lib/postgresql/data
      
  backend:
    build:
      context: .
    container_name: RT-Manager-Backend
    volumes:
      - ~/Documentos/Proyectos/RT-Manager-Backend:/usr/src/app
    restart: always
    ports:
      - 3003:3003
    depends_on:
      - postgres
      - redis
    
  frontend:
    build:
      context: ../RT-Manager-UI
    container_name: RT-Manager-Frontend
    volumes:
      - ~/Documentos/Proyectos/RT-Manager-UI:/usr/src/app
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - backend


